### ISSUE TITLE
Redo SchemaReader

### ISSUE THREAD

**Issue by gossi** [propelorm/Propel3#36]
Reading in a schema in Propel3 (and also Propel2) has been done relative to three different locations (see [Propel2#822](https://github.com/propelorm/Propel2/issues/822#issuecomment-219229235)):

1. `SchemaReader` (which is e.g. invoked by `QuickBuilder`)
2. `AbstractManager`
3. The path from where you execute propel commands (because it matters)

Fun fact here: `SchemaReader` puts external-schema relative to the parent directory of the current schema file, while `AbstractManager` loads external-schema files into the current schema to compensate this. Propel is hacking propel. It is very unreliable to read in an external-schema, it also depends on the path from where you execute propel commands.

**Suggested solution**: Always make an external-schema file relative to the schema that is referring to it.

Second (but that could be already resolved in propel3) is that if schema `a` and `b` exist. schema `a` has schema `b` as an external schema and both have a table of the same name (e.g. `group`) but under different namespace/prefix, propel2 treats them as the same and throws an error because it can't differ between them.

**Suggested solution**: Identify entities by their FQCN (namespace of prefix) and you are easy to go.

I would rewrite the `SchemaReader` to solve the first problem. Would like to get some feedback from you guys before I start.

**Comment by marcj** [comment]
I agree, we should definitely make this consistent.

1) Relative to the schema.xml that contains the import/include should be the way to go. If the path begins with `/` or `c:/` we should treat it as absolute path.

2) Actually our Configuration object already indexes entities by FQCN. I guess we have some places where we still use the base classname. We should definitely switch everywhere to FQCN. However, we have some functionality in `Configuration::hasEntityMap` that allows to use the base class name in the query builder so you don't have to specify always the full rather long class name. This is only supported if the base class name is not ambiguous and is runtime only. It looks different when we see `Database::hasEntity`, it searches the `Entity` model per base class name as fallback, which is why you get the error above I guess. We should make this behaviour in `Database:: hasEntity` optional that it searches also for base class name. The caller should decide if it should search very explicit or if it allows to search by base class name. This is in particular useful for `<relation target="ClassName">`,  so you don't have to write every time the full qualified class name. However, we should still throw an error when `$target=ClassName` is ambiguous.

**Comment by gossi** [comment]
Well, probably a lookup would be good to find an entity only by className. To me the lookup algo would look like the following:

1.  Check if there is a entity with the given name and within the same namespace to where it is connected to (e.g. `<relation>` and would lookup for `className` with the same namespace as in `<entity>`).
2. If it can't be found in the same namespace, look in others
3. If it can't be found, show an error.

So it is up to the user to decide, whether doing sth like `<relation target="ClassName">` or `<relation target="another\name\space\ClassName">`.

Would that make sense?

**Comment by marcj** [comment]
Yes, except that we should throw in 2. an exception if it finds more than one class with the given base class name. 👍

**Comment by cristianoc72** [comment]
Close via #83
