### ISSUE TITLE
Adopt psr-4

### ISSUE THREAD

**Issue by gossi** [propelorm/Propel3#63]
Propel still makes use of psr-0, although it's basically deprecated. Would be easy to use psr-4 with autoload and secondly use `autoload-dev` to load code for tests. Would also flatten directories.

**Comment by stevleibelt** [comment]
I gave [it a try](https://github.com/propelorm/Propel3/pull/85) but it wasn't a funny one and I am a bit unhappy with the current status of this project since Propel1 is still my favorite ORM in PHP.

Why do I need to add the line
```
"minimum-stability": "dev",
```
to my composer.json file to install all dependencies.
From my point of view, it isn't good to have this manual trap since it will maybe scare off developers to push a change or let them push "I think it is working" changes.

Locally and out of the box, I am not able to run all tests (never before or after my change).
After that I thought, how could I improve that?
I must admit, I am currently not deep enough into this project to answer that question. But as a small step, I've created a "run_unit_tests.sh" script in <project root>/bin which contains the content of the Makefile as executable.

How can we easily enable running unit tests?
Provide a docker-compose.yml with a stack of:
* mysql-database
* postgresql-database
* ...
* php environment
would be an option. What do you think?
